### ISSUE TITLE
i am unable to install 

### ISSUE THREAD

**Issue by Next9999** [timataran/ha-bt-bridge#1]
hi

happy to see that the Led are now in HA

i had follow the step but .. the only entity i see is a Device tracker

Any help would be appreciated

![image](https://user-images.githubusercontent.com/54117519/147325917-89f6ba0a-c6ae-404a-b127-40bc9c946733.png)

**Comment by timataran** [comment]
Hi!

It's pleasure to see someone interested in my pet project.

Is mqtt discovery enabled in your HA?
What is being written to log right after app started?
By the way, which run option you selected, native or docker?

**Comment by Next9999** [comment]
mqtt is already running for my heater

i have copy this in my config.yaml
mqtt:
  broker: 192.168.1.180
  port: 1883
  username: MQTT
  password: XXXXXX
  discovery_prefix: home_assistant

timer:
  sleep_seconds: 3

device:
  - type: led_rgb
    MAC: 48:5A:B6:F2:OD:B4
    unique_id: bt_led_light_one
    name: First BT LED light

Error:

Integration error: device - Integration 'device' not found.
Invalid config for [timer]: expected a dictionary for dictionary value @ data['timer']['sleep_seconds']. Got 3. (See /config/configuration.yaml, line 34).

**Comment by timataran** [comment]
>  i have copy this in my config.yaml ...

Do you mean HA configuration file? At least error messages look like they were produced by HomeAssistant..

**Comment by Next9999** [comment]
Yes the Home Assistant configuration

**Comment by timataran** [comment]
Well, obviously documentation need improvement.

I'll try to describe here how it supposed to work.
HomeAssistant runs with mqtt integration enabled, without additional configuration.
This application, bridge, is separate application with its own config. It connects to supported BT device directly (so, the host should support BTLE) and communicates with HomeAssistant over mqtt. 

Once application configured properly and started, after some time device should appear in HA's object list.
![Screenshot from 2021-12-27 22-08-24](https://user-images.githubusercontent.com/28390897/147504590-e3e6635a-3d6e-4831-a78b-721b5377c2fc.png)

**Comment by Next9999** [comment]
How do we install  

docker-compose migrate-to-labels?
or
pip install -r requirements.txt
